//this class Flags creates an array and stores within it the name and flags of different countries and territories
//that can be called to other classes

//country pictures from: https://romanescu.ro/countries/

public class Flags {
    public static Country[] getCountries() {
        return new Country[]{
                new Country("Afghanistan", "https://data.un.org/common/flags/afg_flag.png"),
                new Country("Albania", "https://data.un.org/common/flags/alb_flag.png"),
                new Country("Algeria", "https://data.un.org/common/flags/dza_flag.png"),
                new Country("American Samoa", "https://data.un.org/common/flags/asm_flag.png"),
                new Country("Andorra", "https://data.un.org/common/flags/and_flag.png"),
                new Country("Angola", "https://data.un.org/common/flags/ago_flag.png"),
                new Country("Antigua and Barbuda", "https://data.un.org/common/flags/atg_flag.png"),
                new Country("Argentina", "https://data.un.org/common/flags/arg_flag.png"),
                new Country("Armenia", "https://data.un.org/common/flags/arm_flag.png"),
                new Country("Aruba", "https://data.un.org/common/flags/abw_flag.png"),
                new Country("Australia", "https://data.un.org/common/flags/aus_flag.png"),
                new Country("Austria", "https://data.un.org/common/flags/aut_flag.png"),
                new Country("Azerbaijan", "https://data.un.org/common/flags/aze_flag.png"),
                new Country("Bahamas", "https://data.un.org/common/flags/bhs_flag.png"),
                new Country("Bahrain", "https://data.un.org/common/flags/bhr_flag.png"),
                new Country("Bangladesh", "https://data.un.org/common/flags/bgd_flag.png"),
                new Country("Barbados", "https://data.un.org/common/flags/brb_flag.png"),
                new Country("Belarus", "https://data.un.org/common/flags/blr_flag.png"),
                new Country("Belgium", "https://data.un.org/common/flags/bel_flag.png"),
                new Country("Belize", "https://data.un.org/common/flags/blz_flag.png"),
                new Country("Benin", "https://data.un.org/common/flags/ben_flag.png"),
                new Country("Bermuda", "https://data.un.org/common/flags/bmu_flag.png"),
                new Country("Bhutan", "https://data.un.org/common/flags/btn_flag.png"),
                new Country("Bolivia", "https://data.un.org/common/flags/bol_flag.png"),
                new Country("Bosnia and Herzegovina", "https://data.un.org/common/flags/bih_flag.png"),
                new Country("Botswana", "https://data.un.org/common/flags/bwa_flag.png"),
                new Country("Brazil", "https://data.un.org/common/flags/bra_flag.png"),
                new Country("British Virgin Islands", "https://data.un.org/common/flags/vgb_flag.png"),
                new Country("Brunei", "https://data.un.org/common/flags/brn_flag.png"),
                new Country("Bulgaria", "https://data.un.org/common/flags/bgr_flag.png"),
                new Country("Burkina Faso", "https://data.un.org/common/flags/bfa_flag.png"),
                new Country("Burundi", "https://data.un.org/common/flags/bdi_flag.png"),
                new Country("Cabo Verde", "https://data.un.org/common/flags/cpv_flag.png"),
                new Country("Cambodia", "https://data.un.org/common/flags/khm_flag.png"),
                new Country("Cameroon", "https://data.un.org/common/flags/cmr_flag.png"),
                new Country("Canada", "https://data.un.org/common/flags/can_flag.png"),
                new Country("Cayman Islands", "https://data.un.org/common/flags/cym_flag.png"),
                new Country("Central African Republic", "https://data.un.org/common/flags/caf_flag.png"),
                new Country("Chad", "https://data.un.org/common/flags/tcd_flag.png"),
                new Country("Chile", "https://data.un.org/common/flags/chl_flag.png"),
                new Country("China", "https://data.un.org/common/flags/chn_flag.png"),
                new Country("Colombia", "https://data.un.org/common/flags/col_flag.png"),
                new Country("Comoros", "https://data.un.org/common/flags/com_flag.png"),
                new Country("DRC", "https://data.un.org/common/flags/cod_flag.png"),
                new Country("Congo", "https://data.un.org/common/flags/cog_flag.png"),
                new Country("Costa Rica", "https://data.un.org/common/flags/cri_flag.png"),
                new Country("Cote d'Ivoire", "https://data.un.org/common/flags/civ_flag.png"),
                new Country("Croatia", "https://data.un.org/common/flags/hrv_flag.png"),
                new Country("Cuba", "https://data.un.org/common/flags/cub_flag.png"),
                new Country("Curacao", "https://data.un.org/common/flags/cuw_flag.png"),
                new Country("Cyprus", "https://data.un.org/common/flags/cyp_flag.png"),
                new Country("Czech Republic", "https://data.un.org/common/flags/cze_flag.png"),
                new Country("Denmark", "https://data.un.org/common/flags/dnk_flag.png"),
                new Country("Djibouti", "https://data.un.org/common/flags/dji_flag.png"),
                new Country("Dominica", "https://data.un.org/common/flags/dma_flag.png"),
                new Country("Dominican Republic", "https://data.un.org/common/flags/dom_flag.png"),
                new Country("Ecuador", "https://data.un.org/common/flags/ecu_flag.png"),
                new Country("Egypt", "https://data.un.org/common/flags/egy_flag.png"),
                new Country("El Salvador", "https://data.un.org/common/flags/slv_flag.png"),
                new Country("Equatorial Guinea", "https://data.un.org/common/flags/gnq_flag.png"),
                new Country("Eritrea", "https://data.un.org/common/flags/eri_flag.png"),
                new Country("Estonia", "https://data.un.org/common/flags/est_flag.png"),
                new Country("Eswatini", "https://data.un.org/common/flags/swz_flag.png"),
                new Country("Ethiopia", "https://data.un.org/common/flags/eth_flag.png"),
                new Country("Faroe Islands", "https://data.un.org/common/flags/fro_flag.png"),
                new Country("Fiji", "https://data.un.org/common/flags/fji_flag.png"),
                new Country("Finland", "https://data.un.org/common/flags/fin_flag.png"),
                new Country("France", "https://data.un.org/common/flags/fra_flag.png"),
                new Country("French Polynesia", "https://data.un.org/common/flags/pyf_flag.png"),
                new Country("Gabon", "https://data.un.org/common/flags/gab_flag.png"),
                new Country("Gambia", "https://data.un.org/common/flags/gmb_flag.png"),
                new Country("Georgia", "https://data.un.org/common/flags/geo_flag.png"),
                new Country("Germany", "https://data.un.org/common/flags/deu_flag.png"),
                new Country("Ghana", "https://data.un.org/common/flags/gha_flag.png"),
                new Country("Greece", "https://data.un.org/common/flags/grc_flag.png"),
                new Country("Greenland", "https://data.un.org/common/flags/grl_flag.png"),
                new Country("Grenada", "https://data.un.org/common/flags/grd_flag.png"),
                new Country("Guam", "https://data.un.org/common/flags/gum_flag.png"),
                new Country("Guatemala", "https://data.un.org/common/flags/gtm_flag.png"),
                new Country("Guinea", "https://data.un.org/common/flags/gin_flag.png"),
                new Country("Guinea-Bissau", "https://data.un.org/common/flags/gnb_flag.png"),
                new Country("Guyana", "https://data.un.org/common/flags/guy_flag.png"),
                new Country("Haiti", "https://data.un.org/common/flags/hti_flag.png"),
                new Country("Honduras", "https://data.un.org/common/flags/hnd_flag.png"),
                new Country("Hong Kong", "https://data.un.org/common/flags/hkg_flag.png"),
                new Country("Hungary", "https://data.un.org/common/flags/hun_flag.png"),
                new Country("Iceland", "https://data.un.org/common/flags/isl_flag.png"),
                new Country("India", "https://data.un.org/common/flags/ind_flag.png"),
                new Country("Indonesia", "https://data.un.org/common/flags/idn_flag.png"),
                new Country("Iran", "https://data.un.org/common/flags/irn_flag.png"),
                new Country("Iraq", "https://data.un.org/common/flags/irq_flag.png"),
                new Country("Ireland", "https://data.un.org/common/flags/irl_flag.png"),
                new Country("Isle of Man", "https://data.un.org/common/flags/imn_flag.png"),
                new Country("Israel", "https://data.un.org/common/flags/isr_flag.png"),
                new Country("Italy", "https://data.un.org/common/flags/ita_flag.png"),
                new Country("Jamaica", "https://data.un.org/common/flags/jam_flag.png"),
                new Country("Japan", "https://data.un.org/common/flags/jpn_flag.png"),
                new Country("Jordan", "https://data.un.org/common/flags/jor_flag.png"),
                new Country("Kazakhstan", "https://data.un.org/common/flags/kaz_flag.png"),
                new Country("Kenya", "https://data.un.org/common/flags/ken_flag.png"),
                new Country("Kiribati", "https://data.un.org/common/flags/kir_flag.png"),
                new Country("North Korea", "https://data.un.org/common/flags/prk_flag.png"),
                new Country("South Korea", "https://data.un.org/common/flags/kor_flag.png"),
                new Country("Kuwait", "https://data.un.org/common/flags/kwt_flag.png"),
                new Country("Kyrgyzstan", "https://data.un.org/common/flags/kgz_flag.png"),
                new Country("Laos", "https://data.un.org/common/flags/lao_flag.png"),
                new Country("Latvia", "https://data.un.org/common/flags/lva_flag.png"),
                new Country("Lebanon", "https://data.un.org/common/flags/lbn_flag.png"),
                new Country("Lesotho", "https://data.un.org/common/flags/lso_flag.png"),
                new Country("Liberia", "https://data.un.org/common/flags/lbr_flag.png"),
                new Country("Libya", "https://data.un.org/common/flags/lby_flag.png"),
                new Country("Liechtenstein", "https://data.un.org/common/flags/lie_flag.png"),
                new Country("Lithuania", "https://data.un.org/common/flags/ltu_flag.png"),
                new Country("Luxembourg", "https://data.un.org/common/flags/lux_flag.png"),
                new Country("Macao", "https://data.un.org/common/flags/mac_flag.png"),
                new Country("Madagascar", "https://data.un.org/common/flags/mdg_flag.png"),
                new Country("Malawi", "https://data.un.org/common/flags/mwi_flag.png"),
                new Country("Malaysia", "https://data.un.org/common/flags/mys_flag.png"),
                new Country("Maldives", "https://data.un.org/common/flags/mdv_flag.png"),
                new Country("Mali", "https://data.un.org/common/flags/mli_flag.png"),
                new Country("Malta", "https://data.un.org/common/flags/mlt_flag.png"),
                new Country("Marshall Islands", "https://data.un.org/common/flags/mhl_flag.png"),
                new Country("Mauritania", "https://data.un.org/common/flags/mrt_flag.png"),
                new Country("Mauritius", "https://data.un.org/common/flags/mus_flag.png"),
                new Country("Mexico", "https://data.un.org/common/flags/mex_flag.png"),
                new Country("Micronesia", "https://data.un.org/common/flags/fsm_flag.png"),
                new Country("Moldova", "https://data.un.org/common/flags/mda_flag.png"),
                new Country("Monaco", "https://data.un.org/common/flags/mco_flag.png"),
                new Country("Mongolia", "https://data.un.org/common/flags/mng_flag.png"),
                new Country("Montenegro", "https://data.un.org/common/flags/mne_flag.png"),
                new Country("Morocco", "https://data.un.org/common/flags/mar_flag.png"),
                new Country("Mozambique", "https://data.un.org/common/flags/moz_flag.png"),
                new Country("Myanmar", "https://data.un.org/common/flags/mmr_flag.png"),
                new Country("Namibia", "https://data.un.org/common/flags/nam_flag.png"),
                new Country("Nauru", "https://data.un.org/common/flags/nru_flag.png"),
                new Country("Nepal", "https://data.un.org/common/flags/npl_flag.png"),
                new Country("Netherlands", "https://data.un.org/common/flags/nld_flag.png"),
                new Country("New Caledonia", "https://data.un.org/common/flags/ncl_flag.png"),
                new Country("New Zealand", "https://data.un.org/common/flags/nzl_flag.png"),
                new Country("Nicaragua", "https://data.un.org/common/flags/nic_flag.png"),
                new Country("Niger", "https://data.un.org/common/flags/ner_flag.png"),
                new Country("Nigeria", "https://data.un.org/common/flags/nga_flag.png"),
                new Country("North Macedonia", "https://data.un.org/common/flags/mkd_flag.png"),
                new Country("Northern Mariana Islands", "https://data.un.org/common/flags/mnp_flag.png"),
                new Country("Norway", "https://data.un.org/common/flags/nor_flag.png"),
                new Country("Oman", "https://data.un.org/common/flags/omn_flag.png"),
                new Country("Pakistan", "https://data.un.org/common/flags/pak_flag.png"),
                new Country("Palau", "https://data.un.org/common/flags/plw_flag.png"),
                new Country("Panama", "https://data.un.org/common/flags/pan_flag.png"),
                new Country("Papua New Guinea", "https://data.un.org/common/flags/png_flag.png"),
                new Country("Paraguay", "https://data.un.org/common/flags/pry_flag.png"),
                new Country("Peru", "https://data.un.org/common/flags/per_flag.png"),
                new Country("Philippines", "https://data.un.org/common/flags/phl_flag.png"),
                new Country("Poland", "https://data.un.org/common/flags/pol_flag.png"),
                new Country("Portugal", "https://data.un.org/common/flags/prt_flag.png"),
                new Country("Puerto Rico", "https://data.un.org/common/flags/pri_flag.png"),
                new Country("Qatar", "https://data.un.org/common/flags/qat_flag.png"),
                new Country("Romania", "https://data.un.org/common/flags/rou_flag.png"),
                new Country("Russia", "https://data.un.org/common/flags/rus_flag.png"),
                new Country("Rwanda", "https://data.un.org/common/flags/rwa_flag.png"),
                new Country("Samoa", "https://data.un.org/common/flags/wsm_flag.png"),
                new Country("San Marino", "https://data.un.org/common/flags/smr_flag.png"),
                new Country("Sao Tome and Principe", "https://data.un.org/common/flags/stp_flag.png"),
                new Country("Saudi Arabia", "https://data.un.org/common/flags/sau_flag.png"),
                new Country("Senegal", "https://data.un.org/common/flags/sen_flag.png"),
                new Country("Serbia", "https://data.un.org/common/flags/srb_flag.png"),
                new Country("Seychelles", "https://data.un.org/common/flags/syc_flag.png"),
                new Country("Sierra Leone", "https://data.un.org/common/flags/sle_flag.png"),
                new Country("Singapore", "https://data.un.org/common/flags/sgp_flag.png"),
                new Country("Slovakia", "https://data.un.org/common/flags/svk_flag.png"),
                new Country("Slovenia", "https://data.un.org/common/flags/svn_flag.png"),
                new Country("Solomon Islands", "https://data.un.org/common/flags/slb_flag.png"),
                new Country("Somalia", "https://data.un.org/common/flags/som_flag.png"),
                new Country("South Africa", "https://data.un.org/common/flags/zaf_flag.png"),
                new Country("South Sudan", "https://data.un.org/common/flags/ssd_flag.png"),
                new Country("Spain", "https://data.un.org/common/flags/esp_flag.png"),
                new Country("Sri Lanka", "https://data.un.org/common/flags/lka_flag.png"),
                new Country("St. Lucia", "https://data.un.org/common/flags/lca_flag.png"),
                new Country("St. Vincent and the Grenadines", "https://data.un.org/common/flags/vct_flag.png"),
                new Country("Sudan", "https://data.un.org/common/flags/sdn_flag.png"),
                new Country("Suriname", "https://data.un.org/common/flags/sur_flag.png"),
                new Country("Sweden", "https://data.un.org/common/flags/swe_flag.png"),
                new Country("Switzerland", "https://data.un.org/common/flags/che_flag.png"),
                new Country("Syria", "https://data.un.org/common/flags/syr_flag.png"),
                new Country("Tajikistan", "https://data.un.org/common/flags/tjk_flag.png"),
                new Country("Tanzania", "https://data.un.org/common/flags/tza_flag.png"),
                new Country("Thailand", "https://data.un.org/common/flags/tha_flag.png"),
                new Country("Timor-Leste", "https://data.un.org/common/flags/tls_flag.png"),
                new Country("Togo", "https://data.un.org/common/flags/tgo_flag.png"),
                new Country("Tonga", "https://data.un.org/common/flags/ton_flag.png"),
                new Country("Trinidad and Tobago", "https://data.un.org/common/flags/tto_flag.png"),
                new Country("Tunisia", "https://data.un.org/common/flags/tun_flag.png"),
                new Country("Turkey", "https://data.un.org/common/flags/tur_flag.png"),
                new Country("Turkmenistan", "https://data.un.org/common/flags/tkm_flag.png"),
                new Country("Turks and Caicos", "https://data.un.org/common/flags/tca_flag.png"),
                new Country("Tuvalu", "https://data.un.org/common/flags/tuv_flag.png"),
                new Country("Uganda", "https://data.un.org/common/flags/uga_flag.png"),
                new Country("Ukraine", "https://data.un.org/common/flags/ukr_flag.png"),
                new Country("United Arab Emirates", "https://data.un.org/common/flags/are_flag.png"),
                new Country("United Kingdom", "https://data.un.org/common/flags/gbr_flag.png"),
                new Country("United States", "https://data.un.org/common/flags/usa_flag.png"),
                new Country("Uruguay", "https://data.un.org/common/flags/ury_flag.png"),
                new Country("Uzbekistan", "https://data.un.org/common/flags/uzb_flag.png"),
                new Country("Vanuatu", "https://data.un.org/common/flags/vut_flag.png"),
                new Country("Venezuela", "https://data.un.org/common/flags/ven_flag.png"),
                new Country("Vietnam", "https://data.un.org/common/flags/vnm_flag.png"),
                new Country("Virgin Islands", "https://data.un.org/common/flags/vir_flag.png"),
                new Country("Palestine", "https://data.un.org/common/flags/pse_flag.png"),
                new Country("Yemen", "https://data.un.org/common/flags/yem_flag.png"),
                new Country("Zambia", "https://data.un.org/common/flags/zmb_flag.png"),
                new Country("Zimbabwe", "https://data.un.org/common/flags/zwe_flag.png"),
        };
    }

}